# Generated by Django 6.0.3 on 2026-03-17 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices_app', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workers',
            old_name='Address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='users',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='users',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='users',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='users',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='users',
            name='updated_at',
        ),
    ]
