# Generated by Django 5.2.8 on 2026-03-19 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices_app', '0007_alter_state_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequests',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HomeServices_app.workers'),
        ),
    ]
