# Generated by Django 5.2.8 on 2026-03-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices_app', '0008_servicerequests_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecatogarys',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
