# Generated by Django 6.0.3 on 2026-03-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices_app', '0009_servicecatogarys_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to='aadhar_cards/'),
        ),
    ]
