# Generated by Django 6.0.3 on 2026-03-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeServices_app', '0010_workers_aadhar_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
